// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: registration-request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Reservations.Types {

  /// <summary>Holder for reflection information generated from registration-request.proto</summary>
  public static partial class RegistrationRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for registration-request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RegistrationRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpyZWdpc3RyYXRpb24tcmVxdWVzdC5wcm90bxofZ29vZ2xlL3Byb3RvYnVm",
            "L3RpbWVzdGFtcC5wcm90byKgAwoTUmVnaXN0cmF0aW9uUmVxdWVzdBItCgdz",
            "dHVkZW50GAEgASgLMhwuUmVnaXN0cmF0aW9uUmVxdWVzdC5TdHVkZW50EisK",
            "BmNvdXJzZRgCIAEoCzIbLlJlZ2lzdHJhdGlvblJlcXVlc3QuQ291cnNlEi8K",
            "CG9mZmVyaW5nGAMgASgLMh0uUmVnaXN0cmF0aW9uUmVxdWVzdC5PZmZlcmlu",
            "ZxIrCgdjcmVhdGVkGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFt",
            "cBokCgdTdHVkZW50Eg0KBWVtYWlsGAEgASgJEgoKAmlkGAIgASgJGkQKBkNv",
            "dXJzZRIQCghjb3Vyc2VJZBgBIAEoCRISCgpjb3Vyc2VOYW1lGAIgASgJEhQK",
            "DG51bWJlck9mRGF5cxgDIAEoBRpjCghPZmZlcmluZxISCgpvZmZlcmluZ0lk",
            "GAEgASgJEi0KCXN0YXJ0RGF0ZRgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5U",
            "aW1lc3RhbXASFAoMbnVtYmVyT2ZEYXlzGAMgASgFQhWqAhJSZXNlcnZhdGlv",
            "bnMuVHlwZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Reservations.Types.RegistrationRequest), global::Reservations.Types.RegistrationRequest.Parser, new[]{ "Student", "Course", "Offering", "Created" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Reservations.Types.RegistrationRequest.Types.Student), global::Reservations.Types.RegistrationRequest.Types.Student.Parser, new[]{ "Email", "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Reservations.Types.RegistrationRequest.Types.Course), global::Reservations.Types.RegistrationRequest.Types.Course.Parser, new[]{ "CourseId", "CourseName", "NumberOfDays" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Reservations.Types.RegistrationRequest.Types.Offering), global::Reservations.Types.RegistrationRequest.Types.Offering.Parser, new[]{ "OfferingId", "StartDate", "NumberOfDays" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RegistrationRequest : pb::IMessage<RegistrationRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegistrationRequest> _parser = new pb::MessageParser<RegistrationRequest>(() => new RegistrationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RegistrationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Reservations.Types.RegistrationRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegistrationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegistrationRequest(RegistrationRequest other) : this() {
      student_ = other.student_ != null ? other.student_.Clone() : null;
      course_ = other.course_ != null ? other.course_.Clone() : null;
      offering_ = other.offering_ != null ? other.offering_.Clone() : null;
      created_ = other.created_ != null ? other.created_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegistrationRequest Clone() {
      return new RegistrationRequest(this);
    }

    /// <summary>Field number for the "student" field.</summary>
    public const int StudentFieldNumber = 1;
    private global::Reservations.Types.RegistrationRequest.Types.Student student_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Reservations.Types.RegistrationRequest.Types.Student Student {
      get { return student_; }
      set {
        student_ = value;
      }
    }

    /// <summary>Field number for the "course" field.</summary>
    public const int CourseFieldNumber = 2;
    private global::Reservations.Types.RegistrationRequest.Types.Course course_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Reservations.Types.RegistrationRequest.Types.Course Course {
      get { return course_; }
      set {
        course_ = value;
      }
    }

    /// <summary>Field number for the "offering" field.</summary>
    public const int OfferingFieldNumber = 3;
    private global::Reservations.Types.RegistrationRequest.Types.Offering offering_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Reservations.Types.RegistrationRequest.Types.Offering Offering {
      get { return offering_; }
      set {
        offering_ = value;
      }
    }

    /// <summary>Field number for the "created" field.</summary>
    public const int CreatedFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp created_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Created {
      get { return created_; }
      set {
        created_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RegistrationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RegistrationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Student, other.Student)) return false;
      if (!object.Equals(Course, other.Course)) return false;
      if (!object.Equals(Offering, other.Offering)) return false;
      if (!object.Equals(Created, other.Created)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (student_ != null) hash ^= Student.GetHashCode();
      if (course_ != null) hash ^= Course.GetHashCode();
      if (offering_ != null) hash ^= Offering.GetHashCode();
      if (created_ != null) hash ^= Created.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (student_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Student);
      }
      if (course_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Course);
      }
      if (offering_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Offering);
      }
      if (created_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Created);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (student_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Student);
      }
      if (course_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Course);
      }
      if (offering_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Offering);
      }
      if (created_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Created);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (student_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Student);
      }
      if (course_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Course);
      }
      if (offering_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Offering);
      }
      if (created_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Created);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RegistrationRequest other) {
      if (other == null) {
        return;
      }
      if (other.student_ != null) {
        if (student_ == null) {
          Student = new global::Reservations.Types.RegistrationRequest.Types.Student();
        }
        Student.MergeFrom(other.Student);
      }
      if (other.course_ != null) {
        if (course_ == null) {
          Course = new global::Reservations.Types.RegistrationRequest.Types.Course();
        }
        Course.MergeFrom(other.Course);
      }
      if (other.offering_ != null) {
        if (offering_ == null) {
          Offering = new global::Reservations.Types.RegistrationRequest.Types.Offering();
        }
        Offering.MergeFrom(other.Offering);
      }
      if (other.created_ != null) {
        if (created_ == null) {
          Created = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Created.MergeFrom(other.Created);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (student_ == null) {
              Student = new global::Reservations.Types.RegistrationRequest.Types.Student();
            }
            input.ReadMessage(Student);
            break;
          }
          case 18: {
            if (course_ == null) {
              Course = new global::Reservations.Types.RegistrationRequest.Types.Course();
            }
            input.ReadMessage(Course);
            break;
          }
          case 26: {
            if (offering_ == null) {
              Offering = new global::Reservations.Types.RegistrationRequest.Types.Offering();
            }
            input.ReadMessage(Offering);
            break;
          }
          case 34: {
            if (created_ == null) {
              Created = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Created);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (student_ == null) {
              Student = new global::Reservations.Types.RegistrationRequest.Types.Student();
            }
            input.ReadMessage(Student);
            break;
          }
          case 18: {
            if (course_ == null) {
              Course = new global::Reservations.Types.RegistrationRequest.Types.Course();
            }
            input.ReadMessage(Course);
            break;
          }
          case 26: {
            if (offering_ == null) {
              Offering = new global::Reservations.Types.RegistrationRequest.Types.Offering();
            }
            input.ReadMessage(Offering);
            break;
          }
          case 34: {
            if (created_ == null) {
              Created = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Created);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the RegistrationRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class Student : pb::IMessage<Student>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Student> _parser = new pb::MessageParser<Student>(() => new Student());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Student> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Reservations.Types.RegistrationRequest.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Student() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Student(Student other) : this() {
          email_ = other.email_;
          id_ = other.id_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Student Clone() {
          return new Student(this);
        }

        /// <summary>Field number for the "email" field.</summary>
        public const int EmailFieldNumber = 1;
        private string email_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Email {
          get { return email_; }
          set {
            email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 2;
        private string id_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Id {
          get { return id_; }
          set {
            id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Student);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Student other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Email != other.Email) return false;
          if (Id != other.Id) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Email.Length != 0) hash ^= Email.GetHashCode();
          if (Id.Length != 0) hash ^= Id.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Email.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Email);
          }
          if (Id.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Id);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Email.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Email);
          }
          if (Id.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Id);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Email.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
          }
          if (Id.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Student other) {
          if (other == null) {
            return;
          }
          if (other.Email.Length != 0) {
            Email = other.Email;
          }
          if (other.Id.Length != 0) {
            Id = other.Id;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Email = input.ReadString();
                break;
              }
              case 18: {
                Id = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Email = input.ReadString();
                break;
              }
              case 18: {
                Id = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class Course : pb::IMessage<Course>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Course> _parser = new pb::MessageParser<Course>(() => new Course());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Course> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Reservations.Types.RegistrationRequest.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Course() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Course(Course other) : this() {
          courseId_ = other.courseId_;
          courseName_ = other.courseName_;
          numberOfDays_ = other.numberOfDays_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Course Clone() {
          return new Course(this);
        }

        /// <summary>Field number for the "courseId" field.</summary>
        public const int CourseIdFieldNumber = 1;
        private string courseId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string CourseId {
          get { return courseId_; }
          set {
            courseId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "courseName" field.</summary>
        public const int CourseNameFieldNumber = 2;
        private string courseName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string CourseName {
          get { return courseName_; }
          set {
            courseName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "numberOfDays" field.</summary>
        public const int NumberOfDaysFieldNumber = 3;
        private int numberOfDays_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int NumberOfDays {
          get { return numberOfDays_; }
          set {
            numberOfDays_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Course);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Course other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (CourseId != other.CourseId) return false;
          if (CourseName != other.CourseName) return false;
          if (NumberOfDays != other.NumberOfDays) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (CourseId.Length != 0) hash ^= CourseId.GetHashCode();
          if (CourseName.Length != 0) hash ^= CourseName.GetHashCode();
          if (NumberOfDays != 0) hash ^= NumberOfDays.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (CourseId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(CourseId);
          }
          if (CourseName.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(CourseName);
          }
          if (NumberOfDays != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(NumberOfDays);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (CourseId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(CourseId);
          }
          if (CourseName.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(CourseName);
          }
          if (NumberOfDays != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(NumberOfDays);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (CourseId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(CourseId);
          }
          if (CourseName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(CourseName);
          }
          if (NumberOfDays != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfDays);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Course other) {
          if (other == null) {
            return;
          }
          if (other.CourseId.Length != 0) {
            CourseId = other.CourseId;
          }
          if (other.CourseName.Length != 0) {
            CourseName = other.CourseName;
          }
          if (other.NumberOfDays != 0) {
            NumberOfDays = other.NumberOfDays;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                CourseId = input.ReadString();
                break;
              }
              case 18: {
                CourseName = input.ReadString();
                break;
              }
              case 24: {
                NumberOfDays = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                CourseId = input.ReadString();
                break;
              }
              case 18: {
                CourseName = input.ReadString();
                break;
              }
              case 24: {
                NumberOfDays = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class Offering : pb::IMessage<Offering>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Offering> _parser = new pb::MessageParser<Offering>(() => new Offering());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Offering> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Reservations.Types.RegistrationRequest.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Offering() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Offering(Offering other) : this() {
          offeringId_ = other.offeringId_;
          startDate_ = other.startDate_ != null ? other.startDate_.Clone() : null;
          numberOfDays_ = other.numberOfDays_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Offering Clone() {
          return new Offering(this);
        }

        /// <summary>Field number for the "offeringId" field.</summary>
        public const int OfferingIdFieldNumber = 1;
        private string offeringId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string OfferingId {
          get { return offeringId_; }
          set {
            offeringId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "startDate" field.</summary>
        public const int StartDateFieldNumber = 2;
        private global::Google.Protobuf.WellKnownTypes.Timestamp startDate_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Google.Protobuf.WellKnownTypes.Timestamp StartDate {
          get { return startDate_; }
          set {
            startDate_ = value;
          }
        }

        /// <summary>Field number for the "numberOfDays" field.</summary>
        public const int NumberOfDaysFieldNumber = 3;
        private int numberOfDays_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int NumberOfDays {
          get { return numberOfDays_; }
          set {
            numberOfDays_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Offering);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Offering other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (OfferingId != other.OfferingId) return false;
          if (!object.Equals(StartDate, other.StartDate)) return false;
          if (NumberOfDays != other.NumberOfDays) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (OfferingId.Length != 0) hash ^= OfferingId.GetHashCode();
          if (startDate_ != null) hash ^= StartDate.GetHashCode();
          if (NumberOfDays != 0) hash ^= NumberOfDays.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (OfferingId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(OfferingId);
          }
          if (startDate_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(StartDate);
          }
          if (NumberOfDays != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(NumberOfDays);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (OfferingId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(OfferingId);
          }
          if (startDate_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(StartDate);
          }
          if (NumberOfDays != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(NumberOfDays);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (OfferingId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(OfferingId);
          }
          if (startDate_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartDate);
          }
          if (NumberOfDays != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfDays);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Offering other) {
          if (other == null) {
            return;
          }
          if (other.OfferingId.Length != 0) {
            OfferingId = other.OfferingId;
          }
          if (other.startDate_ != null) {
            if (startDate_ == null) {
              StartDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            StartDate.MergeFrom(other.StartDate);
          }
          if (other.NumberOfDays != 0) {
            NumberOfDays = other.NumberOfDays;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                OfferingId = input.ReadString();
                break;
              }
              case 18: {
                if (startDate_ == null) {
                  StartDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                input.ReadMessage(StartDate);
                break;
              }
              case 24: {
                NumberOfDays = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                OfferingId = input.ReadString();
                break;
              }
              case 18: {
                if (startDate_ == null) {
                  StartDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                input.ReadMessage(StartDate);
                break;
              }
              case 24: {
                NumberOfDays = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
